services:
  - type: web
    name: telegram-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 H.py
    plan: free
    autoDeploy: true
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        value: "8487271564:AAFxXGmmIl73iflDp8EPuNn-5y-AtoH4NhQ"
      - key: OWNER_ID
        value: "7964730489"
      - key: ADMIN_ID
        value: "7964730489"
      - key: YOUR_USERNAME
        value: "@Cyz_778_bot"
      - key: UPDATE_CHANNEL
        value: "https://t.me/Xyzr4"
      - key: PORT
        value: "10000"
